Fix SQL syntax error: remove apostrophes from CSS comments
Error: SQL was breaking on apostrophe in "doesn't"
Fix: Changed "doesn't" to "does not" in CSS comments

This was causing deployment to fail with:
ERROR: syntax error at or near "t"
LINE 88: ...if JS doesn't load) */